# Generated by Django 3.2.3 on 2021-05-20 17:29

import cloudinary.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('seedID', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('maturity', models.CharField(max_length=50)),
                ('countInStock', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.80'), max_digits=5)),
                ('is_oversized', models.BooleanField(default=False)),
                ('addAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('addressee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
