export const SEED_LIST_REQUEST = 'SEED_LIST_REQUEST'
export const SEED_LIST_SUCCESS = 'SEED_LIST_SUCCESS'
export const SEED_LIST_FAIL = 'SEED_LIST_FAIL'

export const SEED_DETAIL_REQUEST = 'SEED_DETAIL_REQUEST'
export const SEED_DETAIL_SUCCESS = 'SEED_DETAIL_SUCCESS'
export const SEED_DETAIL_FAIL = 'SEED_DETAIL_FAIL'