export const ADDRESS_REQUEST = 'ADDRESS_REQUEST'
export const ADDRESS_SUCCESS = 'ADDRESS_SUCCESS'
export const ADDRESS_FAIL = 'ADDRESS_FAIL'

export const ADDRESS_CREATE_REQUEST = 'ADDRESS_CREATE_REQUEST'
export const ADDRESS_CREATE_SUCCESS = 'ADDRESS_CREATE_SUCCESS'
export const ADDRESS_CREATE_FAIL = 'ADDRESS_CREATE_FAIL'
export const ADDRESS_CLEAR = 'ADDRESS_CLEAR'

export const ADDRESS_UPDATE_REQUEST = 'ADDRESS_UPDATE_REQUEST'
export const ADDRESS_UPDATE_SUCCESS = 'ADDRESS_UPDATE_SUCCESS'
export const ADDRESS_UPDATE_FAIL = 'ADDRESS_UPDATE_FAIL'

