export const ADDRESS_REQUEST = 'ADDRESS_REQUEST'
export const ADDRESS_SUCCESS = 'ADDRESS_SUCCESS'
export const ADDRESS_FAIL = 'ADDRESS_FAIL'

export const ADDRESS_SAVE_REQUEST = 'ADDRESS_SAVE_REQUEST'
export const ADDRESS_SAVE_SUCCESS = 'ADDRESS_SAVE_SUCCESS'
export const ADDRESS_SAVE_FAIL = 'ADDRESS_SAVE_FAIL'

export const ADDRESS_UPDATE_REQUEST = 'ADDRESS_UPDATE_REQUEST'
export const ADDRESS_UPDATE_SUCCESS = 'ADDRESS_UPDATE_SUCCESS'
export const ADDRESS_UPDATE_FAIL = 'ADDRESS_UPDATE_FAIL'

